/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.DAO;
import controller.Function;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Sach;
import java.awt.Toolkit;
import java.awt.Image;

/**
 *
 * @author ADMIN
 */
public class CheckTaiKhoan extends javax.swing.JDialog {

    /**
     * Creates new form TimSach
     */
    
    private Home home;
    private ArrayList<Sach> list;
    private int index;
    private DefaultTableModel model;
    
    public CheckTaiKhoan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        home = (Home) parent;
        model = (DefaultTableModel) listSach.getModel();
        this.setTitle("Check Tài Khoản");
        Image iconImage = Toolkit.getDefaultToolkit().getImage("" + "C:\\DoAn\\QuanLyThuVien-master\\src\\view\\logohuce.jpg");
        setIconImage(iconImage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        TimTaiKhoanTheoTen = new javax.swing.JLabel();
        txtCheckTaiKhoan = new javax.swing.JTextField();
        btnCheckTaiKhoan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSach = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TimTaiKhoanTheoTen.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        TimTaiKhoanTheoTen.setText("TÀI KHOẢN CẦN CHECK");
        TimTaiKhoanTheoTen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(TimTaiKhoanTheoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, 65));

        txtCheckTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckTaiKhoanActionPerformed(evt);
            }
        });
        getContentPane().add(txtCheckTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 112, 260, 30));

        btnCheckTaiKhoan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCheckTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/tkiemnhanvien24.png"))); // NOI18N
        btnCheckTaiKhoan.setText("Check");
        btnCheckTaiKhoan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCheckTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckTaiKhoanActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheckTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 111, 100, 31));

        listSach.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        listSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sách", "Tên Sách", "Tên Tác Giả", "Thể Loại", "Hiện Trạng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(listSach);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 575, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BG.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, 710, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCheckTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckTaiKhoanActionPerformed

    private void btnCheckTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckTaiKhoanActionPerformed
        String user = "";
        
        user = new Function().xoacach(txtCheckTaiKhoan.getText().toCharArray());
        user = new Function().xoacachsau(user.toCharArray());
        
        list = new DAO().getlistSachMuon(user);
              
        showTable();                                       
    }//GEN-LAST:event_btnCheckTaiKhoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CheckTaiKhoan dialog = new CheckTaiKhoan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TimTaiKhoanTheoTen;
    private javax.swing.JButton btnCheckTaiKhoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listSach;
    private javax.swing.JTextField txtCheckTaiKhoan;
    // End of variables declaration//GEN-END:variables
 
    public void showTable(){
        model.setRowCount(0);
        for (Sach sach : list){
            model.addRow(new Object[]{
            sach.getMaSach(), sach.getTenSach(), sach.getTenTacGia(), sach.getTheLoai(), sach.getHienTrang()
        });
        }      
    }
}
