/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.DAO;
import controller.Function;
import javax.swing.JOptionPane;
import model.TaiKhoan;
import java.awt.Toolkit;
import java.awt.Image;

/**
 *
 * @author ADMIN
 */
public class DoiMatKhau extends javax.swing.JDialog {

    /**
     * Creates new form DoiMatKhau
     */
    
    private String User;
    private String Pass;
    
    public DoiMatKhau(java.awt.Frame parent, boolean modal, String user, String pass) {
        super(parent, modal);
        initComponents();
        User = user;
        Pass = pass;
        this.setLocationRelativeTo(null);
        this.setTitle("Đổi Mật Khẩu");
        Image iconImage = Toolkit.getDefaultToolkit().getImage("" + "C:\\Users\\Del\\Documents\\NetBeansProjects\\QuanLyThuVien-master\\src\\view\\logohuce.jpg");
        setIconImage(iconImage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        CurrentPass = new javax.swing.JLabel();
        txtCurrentPass = new javax.swing.JPasswordField();
        txtPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 33)); // NOI18N
        jLabel1.setText("Đổi Mật Khẩu Thủ Thư");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        Password.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/matkhaumoi.png"))); // NOI18N
        Password.setText("Nhập Mật Khẩu Mới");
        Password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 260, 40));

        btnConfirm.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnConfirm.setText("Xác Nhận");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, 40));

        btnCancel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCancel.setText("Hủy");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, 40));

        CurrentPass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CurrentPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/password.png"))); // NOI18N
        CurrentPass.setText("Nhập Mật Khẩu Hiện Tại");
        CurrentPass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(CurrentPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 260, 40));
        getContentPane().add(txtCurrentPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 260, 40));
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 260, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BGmo.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 790, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed

        String pass = "";
        String curpass = "";
        
        pass = new Function().xoacach(txtPass.getText().toCharArray());
        pass = new Function().xoacachsau(pass.toCharArray());
        curpass = new Function().xoacach(txtCurrentPass.getText().toCharArray());  
        curpass = new Function().xoacachsau(curpass.toCharArray());
        
        if(curpass.equals(Pass)){
            if(pass.equals("")){
                JOptionPane.showMessageDialog(rootPane, "Mật khẩu không được để trống !");
                txtPass.requestFocus();
            } else if(curpass.equals(pass)) {
                JOptionPane.showMessageDialog(rootPane, "Mật khẩu mới giống mật khẩu hiện tại !");
                txtPass.setText("");
                txtPass.requestFocus();
            } else {
                TaiKhoan taikhoan1 = new TaiKhoan(User, pass);
        
                if(new DAO().DoiMatKhau(taikhoan1)){
                    JOptionPane.showMessageDialog(rootPane, "Đổi mật khẩu thành công !");
                       
                    this.dispose();
                }
            }       
        } else{
            JOptionPane.showMessageDialog(rootPane, "Mật khẩu hiện tại không đúng !");
            txtCurrentPass.setText("");
            txtCurrentPass.requestFocus();
        }
        
    }//GEN-LAST:event_btnConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CurrentPass;
    private javax.swing.JLabel Password;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtCurrentPass;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
