/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DAO;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Sach;
import java.awt.Toolkit;
import java.awt.Image;

/**
 *
 * @author ADMIN
 */
public class HomeSV extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    private ArrayList<Sach> list;
    private DefaultTableModel model;
    private int index;
    private String User;
    private String Pass;

    public HomeSV(String user, String pass) {
        initComponents();
        User = user;
        Pass = pass;
        this.setLocationRelativeTo(null);
        list = new DAO().getlistSachMuon(User);
        model = (DefaultTableModel) listSach.getModel();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setTitle("Home");
        showTable();
        Image iconImage = Toolkit.getDefaultToolkit().getImage("" + "C:\\DoAn\\QuanLyThuVien-master\\src\\view\\logohuce.jpg");
        setIconImage(iconImage);
        
    }
    
    public ArrayList<Sach> getlist(){
        return list = new DAO().getlistSachMuon(User);
    }
    
    public DefaultTableModel getmodel(){
        return model;
    }
    
    public String Luu(String tentaikhoan){
        String luu = tentaikhoan;
       return luu;
    }
    
    public void showTable(){
        list = new DAO().getlistSachMuon(User);
        model.setRowCount(0);
        for (Sach sach : list){
            model.addRow(new Object[]{
            sach.getMaSach(), sach.getTenSach(), sach.getTenTacGia(), sach.getTheLoai(), sach.getHienTrang()
        });
        }      
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSach = new javax.swing.JTable();
        btnTraSach = new javax.swing.JButton();
        btnMuonSach = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnEditPass = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("THƯ VIỆN");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, 60));

        listSach.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        listSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sách", "Tên Sách", "Tên Tác Giả", "Thể Loại", "Hiện Trạng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(listSach);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 653, 230));

        btnTraSach.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTraSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/back.png"))); // NOI18N
        btnTraSach.setText("Trả Sách");
        btnTraSach.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTraSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraSachActionPerformed(evt);
            }
        });
        getContentPane().add(btnTraSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 255, 140, 40));

        btnMuonSach.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnMuonSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/b.png"))); // NOI18N
        btnMuonSach.setText("Mượn Sách");
        btnMuonSach.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMuonSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuonSachActionPerformed(evt);
            }
        });
        getContentPane().add(btnMuonSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 195, 140, 40));

        btnLogout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/thoat.png"))); // NOI18N
        btnLogout.setText("Đăng Xuất");
        btnLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 321, 140, 40));

        btnEditPass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEditPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/password.png"))); // NOI18N
        btnEditPass.setText("Đổi Mật Khẩu");
        btnEditPass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPassActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 140, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BG.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTraSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraSachActionPerformed
        
        TraSach trasach = new TraSach(this, rootPaneCheckingEnabled, User);
        trasach.setVisible(true);
        
    }//GEN-LAST:event_btnTraSachActionPerformed

    private void btnMuonSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuonSachActionPerformed
        TimSach timsach = new TimSach(this, rootPaneCheckingEnabled, User);
        timsach.setVisible(true);
    }//GEN-LAST:event_btnMuonSachActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        DangNhapSV dangnhapsv = new DangNhapSV();
        this.setVisible(false);
        dangnhapsv.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnEditPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPassActionPerformed
        DoiMatKhauSV doimatkhausv = new DoiMatKhauSV(this, rootPaneCheckingEnabled, User, Pass);
        doimatkhausv.setVisible(true);
    }//GEN-LAST:event_btnEditPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditPass;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMuonSach;
    private javax.swing.JButton btnTraSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listSach;
    // End of variables declaration//GEN-END:variables
 
}
