/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DAO;
import controller.Function;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Sach;
import java.awt.Toolkit;
import java.awt.Image;

/**
 *
 * @author ADMIN
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    private ArrayList<Sach> list;
    private DefaultTableModel model;
    private int index;
    private String User;
    private String Pass;
    
    public Home(String user, String pass) {
        initComponents();
        User = user;
        Pass = pass;
        this.setLocationRelativeTo(null);
        list = new DAO().getlistSach();
        model = (DefaultTableModel) listSach.getModel();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setTitle("Home");
        showTable();
        Image iconImage = Toolkit.getDefaultToolkit().getImage("" + "C:\\Users\\Del\\Documents\\NetBeansProjects\\QuanLyThuVien-master\\src\\view\\logohuce.jpg");
        setIconImage(iconImage);
        btnDeleteAll.setVisible(false);
    }
    
    public ArrayList<Sach> getlist(){
        return list = new DAO().getlistSach();
    }
    
    public DefaultTableModel getmodel(){
        return model;
    }
    
    public void showTable(){
        list = new DAO().getlistSach();
        model.setRowCount(0);
        for (Sach sach : list){
            model.addRow(new Object[]{
            sach.getMaSach(), sach.getTenSach(), sach.getTenTacGia(), sach.getTheLoai(), sach.getHienTrang(), sach.getSoLuong()
        });
        }      
    }
    
    public void ThemSach(Sach sach){
        list.add(sach);
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSach = new javax.swing.JTable();
        btnXoaSach = new javax.swing.JButton();
        btnThemSach = new javax.swing.JButton();
        btnSuaSach = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnEditPass = new javax.swing.JButton();
        btnXoaTaiKhoan = new javax.swing.JButton();
        btnCheckTaiKhoan = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        txtTimSachTheoTen = new javax.swing.JTextField();
        btnTimSachTheoTen = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnDeleteAll = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(885, 530));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("QUẢN LÝ THƯ VIỆN");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 380, 60));

        listSach.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        listSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sách", "Tên Sách", "Tên Tác Giả", "Thể Loại", "Hiện Trạng", "Số Lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(listSach);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 610, 320));

        btnXoaSach.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXoaSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/xoa24.png"))); // NOI18N
        btnXoaSach.setText("Xóa Sách");
        btnXoaSach.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXoaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSachActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoaSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 160, 30));

        btnThemSach.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThemSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/add.png"))); // NOI18N
        btnThemSach.setText("Thêm Sách");
        btnThemSach.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSachActionPerformed(evt);
            }
        });
        getContentPane().add(btnThemSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 160, 30));

        btnSuaSach.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSuaSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/sua24.png"))); // NOI18N
        btnSuaSach.setText("Sửa Sách");
        btnSuaSach.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSuaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaSachActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuaSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 160, 30));

        btnLogout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/thoat.png"))); // NOI18N
        btnLogout.setText("Đăng Xuất ");
        btnLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 160, 30));

        btnEditPass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEditPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/matkhaumoi.png"))); // NOI18N
        btnEditPass.setText("Đổi Mật Khẩu");
        btnEditPass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPassActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, 160, 30));

        btnXoaTaiKhoan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXoaTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/xoataikhoan24.png"))); // NOI18N
        btnXoaTaiKhoan.setText("Xóa Tài Khoản");
        btnXoaTaiKhoan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXoaTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTaiKhoanActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoaTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 160, 30));

        btnCheckTaiKhoan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCheckTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/xacnhan.png"))); // NOI18N
        btnCheckTaiKhoan.setText("Check Tài Khoản");
        btnCheckTaiKhoan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCheckTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckTaiKhoanActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheckTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 160, 30));

        btnThongKe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/thongke.png"))); // NOI18N
        btnThongKe.setText("Thống Kê");
        btnThongKe.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        getContentPane().add(btnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 160, 30));
        getContentPane().add(txtTimSachTheoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 390, 30));

        btnTimSachTheoTen.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnTimSachTheoTen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/search_find_magnifier_zoom_glass_icon_196483.png"))); // NOI18N
        btnTimSachTheoTen.setText("Tìm");
        btnTimSachTheoTen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTimSachTheoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimSachTheoTenActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimSachTheoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 80, 31));

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/back.png"))); // NOI18N
        btnBack.setText("Quay Về");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 120, 30));

        btnDeleteAll.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDeleteAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/delete.png"))); // NOI18N
        btnDeleteAll.setText("Xóa Hết Sách");
        btnDeleteAll.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAllActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 160, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BG3.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSachActionPerformed
        XoaSach xoasach = new XoaSach(this, rootPaneCheckingEnabled);
        xoasach.setVisible(true);      
    }//GEN-LAST:event_btnXoaSachActionPerformed

    private void btnThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSachActionPerformed
        ThemSach themsach = new ThemSach(this, rootPaneCheckingEnabled);
        themsach.setVisible(true);
    }//GEN-LAST:event_btnThemSachActionPerformed

    private void btnSuaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaSachActionPerformed
        index = listSach.getSelectedRow();
        int check = list.size();
        if(check == 0){
            JOptionPane.showMessageDialog(rootPane, "Thư viện không co sách để sửa !");
        } else if (index < 0){
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn sách để sửa !");
        } else {
            SuaSach suasach = new SuaSach(this, rootPaneCheckingEnabled);
            suasach.setEditData(list.get(index));
            suasach.setVisible(true);
        }
    }//GEN-LAST:event_btnSuaSachActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        DangNhap dangnhap = new DangNhap();
        this.setVisible(false);
        dangnhap.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnEditPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPassActionPerformed
        DoiMatKhau doimatkhau = new DoiMatKhau(this, rootPaneCheckingEnabled, User, Pass);
        doimatkhau.setVisible(true);
    }//GEN-LAST:event_btnEditPassActionPerformed

    private void btnXoaTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTaiKhoanActionPerformed
        XoaTaiKhoan xoatk = new XoaTaiKhoan(this, rootPaneCheckingEnabled);
        xoatk.setVisible(true);
    }//GEN-LAST:event_btnXoaTaiKhoanActionPerformed

    private void btnCheckTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckTaiKhoanActionPerformed
        CheckTaiKhoan checktaikhoan = new CheckTaiKhoan(this, rootPaneCheckingEnabled);
        checktaikhoan.setVisible(true);
    }//GEN-LAST:event_btnCheckTaiKhoanActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        ThongKe thongke = new ThongKe(this, rootPaneCheckingEnabled);
        thongke.setVisible(true);
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnTimSachTheoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimSachTheoTenActionPerformed
        String TenSach = "";

        TenSach = new Function().xoacach(txtTimSachTheoTen.getText().toCharArray());
        TenSach = new Function().xoacachsau(TenSach.toCharArray());
        TenSach = new Function().inhoachudau(TenSach.toCharArray());

        Sach sach = new Sach(TenSach);

        getSelectedSach(sach);
    }//GEN-LAST:event_btnTimSachTheoTenActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        showTable();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAllActionPerformed
        Object[] options = { "Yes", "No" };
        int n = JOptionPane.showOptionDialog(null, "Bạn có chắc muốn xóa hết sách ?", "Confirm to Delete?",
        JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
        if (n == 0){
            if(new DAO().XoaAllSach()){
            new DAO().XoaAllSachMuon();
            JOptionPane.showMessageDialog(rootPane, "Xóa thành công !");
            showTable();
        }
        }
    }//GEN-LAST:event_btnDeleteAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckTaiKhoan;
    private javax.swing.JButton btnDeleteAll;
    private javax.swing.JButton btnEditPass;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSuaSach;
    private javax.swing.JButton btnThemSach;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnTimSachTheoTen;
    private javax.swing.JButton btnXoaSach;
    private javax.swing.JButton btnXoaTaiKhoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listSach;
    private javax.swing.JTextField txtTimSachTheoTen;
    // End of variables declaration//GEN-END:variables

    public void SuaSach(Sach sach) {
        list.get(index).setTenSach(sach.getTenSach());
        list.get(index).setTenTacGia(sach.getTenTacGia());
        list.get(index).setTheLoai(sach.getTheLoai());
        list.get(index).setHienTrang(sach.getHienTrang());
        list.get(index).setSoLuong(sach.getSoLuong());
        showTable();
    }    

    public void getSelectedSach(Sach sach) {
        list = new DAO().getSelectedSach(sach);
        model.setRowCount(0);
        for (Sach sach1 : list){
            model.addRow(new Object[]{
            sach1.getMaSach(), sach1.getTenSach(), sach1.getTenTacGia(), sach1.getTheLoai(), sach1.getHienTrang(), sach1.getSoLuong()
        });
        }    
    }
}
