/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.DAO;
import controller.Function;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Sach;
import java.awt.Toolkit;
import java.awt.Image;

/**
 *
 * @author ADMIN
 */
public class TimSach extends javax.swing.JDialog {

    /**
     * Creates new form TimSach
     */
    
    private HomeSV homesv;
    private ArrayList<Sach> list;
    private int index;
    private DefaultTableModel model;
    private String User;
    
    public TimSach(java.awt.Frame parent, boolean modal, String user) {
        super(parent, modal);
        initComponents();
        User = user;
        this.setLocationRelativeTo(null);
        homesv = (HomeSV) parent;
        model = (DefaultTableModel) listSelectedSach.getModel();
        this.setTitle("Mượn Sách");
        showTable();
        Image iconImage = Toolkit.getDefaultToolkit().getImage("" + "C:\\DoAn\\QuanLyThuVien-master\\src\\view\\logohuce.jpg");
        setIconImage(iconImage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TimSachTheoTen = new javax.swing.JLabel();
        txtTimSachTheoTen = new javax.swing.JTextField();
        btnTimSachTheoTen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSelectedSach = new javax.swing.JTable();
        btnMuonSach = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TimSachTheoTen.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        TimSachTheoTen.setForeground(new java.awt.Color(255, 255, 255));
        TimSachTheoTen.setText("TÌM KIẾM SÁCH");
        TimSachTheoTen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(TimSachTheoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, 60));

        txtTimSachTheoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimSachTheoTenActionPerformed(evt);
            }
        });
        getContentPane().add(txtTimSachTheoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 350, 30));

        btnTimSachTheoTen.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnTimSachTheoTen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/search_find_magnifier_zoom_glass_icon_196483.png"))); // NOI18N
        btnTimSachTheoTen.setText("Tìm");
        btnTimSachTheoTen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTimSachTheoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimSachTheoTenActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimSachTheoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 80, 31));

        listSelectedSach.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        listSelectedSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sách", "Tên Sách", "Tên Tác Giả", "Thể Loại", "Hiện Trạng", "Số Lượng", "Mượn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(listSelectedSach);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 540, 200));

        btnMuonSach.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnMuonSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/count.jpg"))); // NOI18N
        btnMuonSach.setText("Mượn");
        btnMuonSach.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMuonSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuonSachActionPerformed(evt);
            }
        });
        getContentPane().add(btnMuonSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 90, 31));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/a1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 680, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimSachTheoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimSachTheoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimSachTheoTenActionPerformed

    private void btnTimSachTheoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimSachTheoTenActionPerformed
        String TenSach = ""; 
   
        TenSach = new Function().xoacach(txtTimSachTheoTen.getText().toCharArray());
        TenSach = new Function().xoacachsau(TenSach.toCharArray());
        TenSach = new Function().inhoachudau(TenSach.toCharArray());
        
        Sach sach = new Sach(TenSach);
              
        getSelectedSach(sach);                                       
    }//GEN-LAST:event_btnTimSachTheoTenActionPerformed

    private void btnMuonSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuonSachActionPerformed
        index = listSelectedSach.getSelectedRow();
 
        if (index < 0){
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn sách để mượn !");
        } else if (list.get(index).getSoLuong() <= 0){
            JOptionPane.showMessageDialog(rootPane, "Sách đã được mượn hết !");
        } else {
            for (int i = 0; i < listSelectedSach.getRowCount(); i++) {
            Boolean chek = Boolean.valueOf(listSelectedSach.getValueAt(i, 6).toString());
            if (chek){
                int masach = Integer.parseInt(listSelectedSach.getValueAt(i, 0).toString());               
                Sach sach = new DAO().TimSach(masach);
                
                if(new DAO().MuonSach(sach, User)){
                    int soluong = 0;
                
                    soluong = new DAO().getSoLuongSach(sach) - 1;
                
                    if(new DAO().setSoLuongSach(sach, soluong)){
                        int luotmuon = 0;
                    
                        luotmuon = new DAO().getLuotMuon(sach) + 1;
                    
                        if(new DAO().setLuotMuon(sach, luotmuon)){

                        }                   
                    }
                }                                
            }                      
        }
            JOptionPane.showMessageDialog(rootPane, "Mượn thành công !");
        
            showTable();
            homesv.showTable();         
        }
    }//GEN-LAST:event_btnMuonSachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TimSachTheoTen;
    private javax.swing.JButton btnMuonSach;
    private javax.swing.JButton btnTimSachTheoTen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listSelectedSach;
    private javax.swing.JTextField txtTimSachTheoTen;
    // End of variables declaration//GEN-END:variables

    public void getSelectedSach(Sach sach) {
        list = new DAO().getSelectedSach(sach);
        model.setRowCount(0);
        for (Sach sach1 : list){
            model.addRow(new Object[]{
            sach1.getMaSach(), sach1.getTenSach(), sach1.getTenTacGia(), sach1.getTheLoai(), sach1.getHienTrang(), sach1.getSoLuong(), false
        });
        }    
    }
    
    public void showTable(){
        list = new DAO().getlistSach();
        model.setRowCount(0);
        for (Sach sach1 : list){
            model.addRow(new Object[]{
            sach1.getMaSach(), sach1.getTenSach(), sach1.getTenTacGia(), sach1.getTheLoai(), sach1.getHienTrang(), sach1.getSoLuong(), false
        });
        }      
    }
}
